#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "config" / "coding-agent-catalog.json"
TARGET = ROOT / "src" / "grabowski_coding_agent_catalog_data.py"


def source_value() -> tuple[bytes, bytes, str, str]:
    source_bytes = SOURCE.read_bytes()
    try:
        value = json.loads(source_bytes.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise RuntimeError("coding-agent catalog is not valid UTF-8 JSON") from exc
    if not isinstance(value, dict):
        raise RuntimeError("coding-agent catalog root must be an object")
    canonical = json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")
    return (
        source_bytes,
        canonical,
        hashlib.sha256(source_bytes).hexdigest(),
        hashlib.sha256(canonical).hexdigest(),
    )


def render() -> str:
    source_bytes, canonical, source_sha256, canonical_sha256 = source_value()
    del source_bytes
    literal = repr(canonical.decode("utf-8"))
    return (
        "# Generated by tools/build_coding_agent_catalog_data.py. Do not edit.\n"
        "from __future__ import annotations\n\n"
        f"CATALOG_SOURCE_SHA256 = {source_sha256!r}\n"
        f"CATALOG_CANONICAL_SHA256 = {canonical_sha256!r}\n"
        f"CATALOG_JSON = {literal}\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    rendered = render()
    if args.write:
        TARGET.write_text(rendered, encoding="utf-8")
        print(TARGET.relative_to(ROOT))
        return 0
    try:
        current = TARGET.read_text(encoding="utf-8")
    except FileNotFoundError:
        print(f"generated catalog data missing: {TARGET}", file=sys.stderr)
        return 1
    if current != rendered:
        print("generated coding-agent catalog data is stale", file=sys.stderr)
        return 1
    print("coding-agent catalog data: current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
