from __future__ import annotations

from typing import Any


def operator_relay_protocol() -> dict[str, Any]:
    """Return the canonical role-bound operator-routing contract."""
    return {
        "name": "Operator Relay v0",
        "doc_path": "docs/blocked-action-protocol-v0.md",
        "rule": "Authority follows explicit controller and lane-role bindings, never model identity. The controller owns planning, integration, merge, deployment and closeout; a scoped writer may implement, test, commit, push and create or update a pull request only inside its bound lane; reviewers and observers remain read-only.",
        "control_loop": [
            "typed_grabowski_tool",
            "grabowski_micro_task",
            "receipt_before_next_step",
        ],
        "execution_priority": [
            "chatgpt_operator",
            "claude",
            "codex",
            "antigravity",
            "opencode",
            "openhands",
            "cline",
        ],
        "review_and_contrast_agent_priority": [
            "claude",
            "codex",
            "antigravity",
            "opencode",
            "openhands",
            "cline",
        ],
        "coding_agent_priority": [
            "claude",
            "codex",
            "antigravity",
            "opencode",
            "openhands",
            "cline",
        ],
        "coding_agent_priority_semantics": "routing_preference_not_authority",
        "execution_priority_semantics": "routing_preference_not_model_authority",
        "authority_principle": "model_identity_does_not_grant_authority",
        "bureau_task_required_for_direct_user_work": False,
        "owner_authorized_automatic_execution": True,
        "delegated_scoped_writers_allowed": True,
        "direct_user_lifecycle_source": "work_lane",
        "controller_only_effects": [
            "merge",
            "deployment",
            "bureau_terminalization",
            "closeout",
        ],
        "overlapping_writer_invariant": "one_authoritative_mutating_writer_per_overlapping_resource_lane",
        "parallel_disjoint_lanes_allowed": True,
        "fail_closed_conditions": [
            "live_overlapping_foreign_writer_or_lease",
            "outcome_unknown",
            "invalid_runtime_or_audit_state",
            "missing_cost_approval",
        ],
        "authority_roles": {
            "controller": {
                "authoritative": True,
                "may_delegate": True,
                "owns": [
                    "planning",
                    "integration",
                    "merge",
                    "deployment",
                    "closeout",
                ],
            },
            "scoped_writer": {
                "authoritative_within_lane": True,
                "requires": [
                    "explicit_lane",
                    "resource_scope",
                    "controller_binding",
                ],
                "allowed_effects": [
                    "implement",
                    "test",
                    "commit",
                    "push",
                    "pull_request_create_or_update",
                ],
                "forbidden_without_controller": [
                    "merge",
                    "deployment",
                    "bureau_terminalization",
                    "closeout",
                ],
            },
            "reviewer": {
                "authoritative": False,
                "mode": "advisory",
                "read_only": True,
            },
            "observer": {
                "authoritative": False,
                "mode": "evidence",
                "read_only": True,
            },
        },
        "workspace_execution_model": {
            "default": "controller_direct_or_delegated_scoped_writer",
            "lane_owner": "controller",
            "operator_self_serves_lanes": [
                "captain",
                "writer",
                "tests",
                "review",
                "integration",
                "merge",
                "deployment",
                "closeout",
            ],
            "role_evidence_isolated": True,
            "workspace_not_universal": True,
            "direct_operator_for": [
                "unscoped_or_ambiguous_work",
                "integration",
                "merge",
                "deployment",
                "closeout",
                "recovery",
            ],
            "full_workspace_for": [],
            "external_agent_delegation": "role_bound_scoped_writer_reviewer_or_observer",
            "delegation_triggers": [
                "bounded_implementation_lane",
                "disjoint_capacity_lane",
                "independent_review",
                "security_or_architecture_review",
                "explicit_contrast_request",
                "multiple_plausible_implementations_for_comparison",
            ],
            "external_programming_modes": ["scoped_writer", "competitor", "contrast"],
            "max_external_candidates": 2,
            "external_candidate_authority": "role_dependent",
            "external_primary_writer_forbidden": False,
            "external_primary_reviewer_forbidden": True,
            "capacity_fallback_to_external_writer": True,
            "automatic_patch_apply": False,
            "automatic_winner_selection": False,
        },
        "operator_first_for": [
            "task_decomposition",
            "integration",
            "merge",
            "deployment",
            "closeout",
            "recovery",
        ],
        "routing_roles": {
            "complex_code_task": "controller_or_lane_bound_scoped_writer",
            "quick_light_reasoning": "controller",
            "local_micro_reasoning": "controller",
            "shell_or_git_grip": "grabowski_task",
            "security_or_architecture_review": "independent_reviewer_then_controller_verification",
            "session_resume": "controller",
            "memory_prioritization": "bureau",
            "implementation": "controller_or_lane_bound_scoped_writer",
            "patch_file_relay": "operator_patch_relay",
            "patch_fallback": "controller",
            "audit": "grabowski_git",
            "repo_state_context": "typed_git_checkout_reads",
        },
        "does_not_establish": [
            "new_privileges",
            "automatic_merge",
            "automatic_push",
            "automatic_deploy",
            "model_identity_authority",
            "free_shell_as_default_path",
            "durable_agent_autonomy_without_lane_binding",
        ],
    }
